# Player.create!([
#   {name: "Andrew Montesantos", number: 22, position: "Pitcher", team_id: 1},
#   {name: "Angel Dejesus", number: 24, position: "Left Field", team_id: 1},
#   {name: "Bill Nestos", number: 98, position: "Catcher", team_id: 1},
#   {name: "Chris Bowen", number: 69, position: "Left Field", team_id: 1},
#   {name: "Christian Erickson", number: 16, position: "Short Stop", team_id: 1},
#   {name: "Don Granzin", number: 0, position: "First Base", team_id: 1},
#   {name: "Eddie Santiago", number: 28, position: "Third Base", team_id: 1},
#   {name: "Gary Ramos", number: 26, position: "Center Field", team_id: 1},
#   {name: "Jake Karmel", number: 12, position: "Pitcher", team_id: 1},
#   {name: "Joe Cosentino", number: 17, position: "First Base", team_id: 1},
#   {name: "John Montesantos", number: 19, position: "First Base", team_id: 1},
#   {name: "Kevin Jung", number: 3, position: "Catcher", team_id: 1},
#   {name: "Luis Berrios", number: 25, position: "Pitcher", team_id: 1},
#   {name: "Nick Kafkis", number: 46, position: "Right Field", team_id: 1},
#   {name: "Ricardo Uriostegui", number: 0, position: "Second Base", team_id: 1},
#   {name: "Steve Eanet", number: 4, position: "Second Base", team_id: 1},
#   {name: "William Alvarez", number: 0, position: "Second Base", team_id: 1},
#   {name: "Zabit Isai", number: 0, position: "Center Field", team_id: 1},
#   {name: "Zach Strimel", number: 17, position: "Third Base", team_id: 1},
#   {name: "Lelia Goodwin", number: 52, position: "2B", team_id: 2},
#   {name: "Erline Morissette", number: 33, position: "RF", team_id: 2},
#   {name: "Caitlyn Friesen", number: 39, position: "C", team_id: 2},
#   {name: "Willis Purdy", number: 8, position: "CF", team_id: 2},
#   {name: "Ariel Leuschke", number: 52, position: "CF", team_id: 2},
#   {name: "Garth Satterfield", number: 93, position: "SS", team_id: 2},
#   {name: "Brain Heidenreich", number: 61, position: "CF", team_id: 2},
#   {name: "Prof. Cristopher Davis", number: 31, position: "1B", team_id: 2},
#   {name: "Dorian Dicki", number: 42, position: "2B", team_id: 2},
#   {name: "Carmina Pouros", number: 51, position: "SS", team_id: 2},
#   {name: "Rodger Wilderman", number: 22, position: "SS", team_id: 2},
#   {name: "Mira Quigley", number: 47, position: "RF", team_id: 2},
#   {name: "Ms. Sharee Kessler", number: 25, position: "P", team_id: 2},
#   {name: "Dusty Koss CPA", number: 74, position: "2B", team_id: 2},
#   {name: "Joesph Jaskolski", number: 4, position: "RF", team_id: 2},
#   {name: "Takako Braun", number: 60, position: "2B", team_id: 3},
#   {name: "Brice Konopelski", number: 90, position: "P", team_id: 3},
#   {name: "Stefanie Roob", number: 55, position: "3B", team_id: 3},
#   {name: "Nikole Vandervort II", number: 72, position: "1B", team_id: 3},
#   {name: "Rayford Lemke", number: 74, position: "RF", team_id: 3},
#   {name: "Mrs. Valrie Mueller", number: 84, position: "P", team_id: 3},
#   {name: "Msgr. Shannon Kutch", number: 79, position: "2B", team_id: 3},
#   {name: "Magdalen Okuneva", number: 66, position: "CF", team_id: 3},
#   {name: "Paulette Durgan", number: 91, position: "C", team_id: 3},
#   {name: "Alfredia Rath", number: 93, position: "3B", team_id: 3},
#   {name: "Mrs. Drew Zieme", number: 17, position: "C", team_id: 3},
#   {name: "Zackary Koepp", number: 95, position: "RF", team_id: 3},
#   {name: "Tressa Abshire", number: 42, position: "CF", team_id: 3},
#   {name: "Douglas Corwin", number: 81, position: "C", team_id: 3},
#   {name: "Colby Senger", number: 94, position: "LF", team_id: 3},
#   {name: "Neil Rolfson CPA", number: 31, position: "C", team_id: 4},
#   {name: "Sophia Kilback", number: 76, position: "1B", team_id: 4},
#   {name: "Issac Fay Esq.", number: 57, position: "LF", team_id: 4},
#   {name: "Emmitt Mohr", number: 51, position: "C", team_id: 4},
#   {name: "Maynard Kilback", number: 85, position: "1B", team_id: 4},
#   {name: "Hubert Christiansen MD", number: 93, position: "CF", team_id: 4},
#   {name: "Francis Kshlerin", number: 37, position: "RF", team_id: 4},
#   {name: "The Hon. Margeret Kuhn", number: 57, position: "RF", team_id: 4},
#   {name: "Rolanda Kling DO", number: 40, position: "LF", team_id: 4},
#   {name: "Lawrence Sauer", number: 9, position: "RF", team_id: 4},
#   {name: "Raymon Kunde", number: 73, position: "2B", team_id: 4},
#   {name: "Karin Bauch Sr.", number: 14, position: "2B", team_id: 4},
#   {name: "Mrs. Refugio Erdman", number: 27, position: "C", team_id: 4},
#   {name: "Teddy Schowalter III", number: 76, position: "RF", team_id: 4},
#   {name: "Mafalda Russel DDS", number: 34, position: "1B", team_id: 4},
#   {name: "Roosevelt Jacobi V", number: 38, position: "CF", team_id: 5},
#   {name: "Walker Gottlieb", number: 40, position: "3B", team_id: 5},
#   {name: "Alverta Schiller", number: 76, position: "SS", team_id: 5},
#   {name: "Edelmira Quitzon", number: 2, position: "3B", team_id: 5},
#   {name: "Kenneth Turcotte DO", number: 11, position: "3B", team_id: 5},
#   {name: "Msgr. Monika Luettgen", number: 17, position: "SS", team_id: 5},
#   {name: "Tobias Hettinger Sr.", number: 40, position: "CF", team_id: 5},
#   {name: "Jesse Kunze", number: 75, position: "RF", team_id: 5},
#   {name: "Delmar Durgan", number: 3, position: "2B", team_id: 5},
#   {name: "Lazaro Macejkovic Esq.", number: 37, position: "1B", team_id: 5},
#   {name: "Reynaldo Farrell", number: 39, position: "P", team_id: 5},
#   {name: "Gina Reichel", number: 42, position: "P", team_id: 5},
#   {name: "Mohammad Zboncak", number: 15, position: "P", team_id: 5},
#   {name: "Christin Feest", number: 62, position: "CF", team_id: 5},
#   {name: "Lauryn Harber MD", number: 52, position: "SS", team_id: 5},
#   {name: "Royce Blanda", number: 74, position: "RF", team_id: 6},
#   {name: "Mckenzie Torp DO", number: 65, position: "2B", team_id: 6},
#   {name: "Hildred Fay", number: 60, position: "3B", team_id: 6},
#   {name: "Andy Frami", number: 96, position: "3B", team_id: 6},
#   {name: "Leanna Feeney", number: 60, position: "1B", team_id: 6},
#   {name: "Jeremiah Murphy", number: 34, position: "P", team_id: 6},
#   {name: "Josephina Hartmann", number: 43, position: "LF", team_id: 6},
#   {name: "Stewart Rogahn V", number: 81, position: "1B", team_id: 6},
#   {name: "Vern Stehr", number: 38, position: "C", team_id: 6},
#   {name: "Cory Gerlach", number: 61, position: "LF", team_id: 6},
#   {name: "Elton Gusikowski", number: 88, position: "P", team_id: 6},
#   {name: "Fr. Ai McClure", number: 78, position: "RF", team_id: 6},
#   {name: "Claud Rohan", number: 16, position: "P", team_id: 6},
#   {name: "Lyndon Pfeffer", number: 9, position: "2B", team_id: 6},
#   {name: "Mr. Ozell Little", number: 20, position: "CF", team_id: 6},
#   {name: "Waylon Will", number: 61, position: "CF", team_id: 7},
#   {name: "Fr. Cristobal Little", number: 46, position: "P", team_id: 7},
#   {name: "Harland Crist", number: 40, position: "LF", team_id: 7},
#   {name: "Pres. Houston Corwin", number: 93, position: "1B", team_id: 7},
#   {name: "Aleen Von LLD", number: 12, position: "RF", team_id: 7},
#   {name: "Everett Schaden", number: 30, position: "C", team_id: 7},
#   {name: "Miss Almeda Schimmel", number: 59, position: "SS", team_id: 7},
#   {name: "Hilario Nitzsche", number: 20, position: "2B", team_id: 7},
#   {name: "Brandi Hessel Jr.", number: 59, position: "3B", team_id: 7},
#   {name: "Ms. Frida Boyle", number: 57, position: "P", team_id: 7},
#   {name: "Aracelis Murray", number: 43, position: "2B", team_id: 7},
#   {name: "Ramon Lakin", number: 92, position: "RF", team_id: 7},
#   {name: "Leon Gorczany Jr.", number: 65, position: "C", team_id: 7},
#   {name: "Emelia Orn", number: 2, position: "RF", team_id: 7},
#   {name: "Kerstin Schultz", number: 77, position: "C", team_id: 7},
#   {name: "Una Cole", number: 30, position: "1B", team_id: 8},
#   {name: "Jesus Johnson", number: 13, position: "C", team_id: 8},
#   {name: "Ricardo Senger", number: 84, position: "1B", team_id: 8},
#   {name: "Edmundo Dooley", number: 41, position: "SS", team_id: 8},
#   {name: "Fr. Stacey Hauck", number: 22, position: "LF", team_id: 8},
#   {name: "Bradford Dicki", number: 75, position: "CF", team_id: 8},
#   {name: "Gov. Lorenzo Cormier", number: 30, position: "SS", team_id: 8},
#   {name: "Zena Kertzmann", number: 89, position: "RF", team_id: 8},
#   {name: "Regina Bechtelar", number: 21, position: "SS", team_id: 8},
#   {name: "Robbie Reinger DO", number: 39, position: "2B", team_id: 8},
#   {name: "Gov. Maryetta Abernathy", number: 28, position: "C", team_id: 8},
#   {name: "Rebeca Morar", number: 13, position: "3B", team_id: 8},
#   {name: "Jude Hermiston", number: 28, position: "3B", team_id: 8},
#   {name: "Amb. Gonzalo Williamson", number: 99, position: "2B", team_id: 8},
#   {name: "Margy Gleichner", number: 3, position: "3B", team_id: 8},
#   {name: "Ellsworth Becker", number: 28, position: "CF", team_id: 9},
#   {name: "Max Schmidt", number: 26, position: "LF", team_id: 9},
#   {name: "Mr. Natalya Corwin", number: 20, position: "RF", team_id: 9},
#   {name: "Bill Murazik", number: 40, position: "P", team_id: 9},
#   {name: "Dorathy Adams", number: 5, position: "C", team_id: 9},
#   {name: "Rev. Lizzette McCullough", number: 95, position: "SS", team_id: 9},
#   {name: "Ted Dooley", number: 39, position: "SS", team_id: 9},
#   {name: "Emil Klein", number: 56, position: "SS", team_id: 9},
#   {name: "Chi Langworth DDS", number: 57, position: "2B", team_id: 9},
#   {name: "Marcelle Johns", number: 52, position: "P", team_id: 9},
#   {name: "Rep. Wanda Hand", number: 95, position: "SS", team_id: 9},
#   {name: "Eliseo Wintheiser", number: 43, position: "2B", team_id: 9},
#   {name: "Larhonda Runte", number: 11, position: "1B", team_id: 9},
#   {name: "Brianne Schuppe", number: 60, position: "SS", team_id: 9},
#   {name: "Rolf Abshire", number: 30, position: "2B", team_id: 9},
#   {name: "Seth Gottlieb", number: 78, position: "2B", team_id: 10},
#   {name: "Cleo Upton", number: 97, position: "RF", team_id: 10},
#   {name: "Gov. Jefferey Sauer", number: 4, position: "2B", team_id: 10},
#   {name: "Alex D'Amore", number: 91, position: "3B", team_id: 10},
#   {name: "Bradford Lemke", number: 47, position: "C", team_id: 10},
#   {name: "Ozzie Wintheiser LLD", number: 16, position: "LF", team_id: 10},
#   {name: "Micheal Weissnat", number: 12, position: "3B", team_id: 10},
#   {name: "Hugh VonRueden", number: 53, position: "LF", team_id: 10},
#   {name: "Marlo Huels", number: 19, position: "3B", team_id: 10},
#   {name: "Jodie Boyer", number: 98, position: "C", team_id: 10},
#   {name: "Juana Spencer I", number: 37, position: "CF", team_id: 10},
#   {name: "Albertha Willms", number: 89, position: "CF", team_id: 10},
#   {name: "Randy Lehner", number: 37, position: "C", team_id: 10},
#   {name: "Isreal Wisozk", number: 84, position: "SS", team_id: 10},
#   {name: "Oda Ankunding", number: 49, position: "P", team_id: 10}
# ])
# Team.create!([
#   {name: "Bombers", wins: 2, losses: 0, ties: 1, bio: nil},
#   {name: "Indios", wins: 2, losses: 1, ties: 1, bio: nil},
#   {name: "Wolverines", wins: 2, losses: 1, ties: 1, bio: nil},
#   {name: "Firebirds", wins: 1, losses: 1, ties: 1, bio: nil},
#   {name: "Lobos", wins: 0, losses: 2, ties: 1, bio: nil},
#   {name: "Reds", wins: 2, losses: 1, ties: 1, bio: nil},
#   {name: "Barbarians", wins: 1, losses: 1, ties: 1, bio: nil},
#   {name: "Red Devils", wins: 1, losses: 1, ties: 1, bio: nil},
#   {name: "Trash Pandas", wins: 2, losses: 1, ties: 1, bio: nil},
#   {name: "Cobras", wins: 0, losses: 2, ties: 1, bio: nil}
# ])
